ALTER TABLE food.daily_meal_ingredient ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE food.daily_meal_ingredient ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM_INIT';
ALTER TABLE food.daily_meal_ingredient ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE food.daily_meal_ingredient ADD COLUMN updated_by VARCHAR(255);

ALTER TABLE food.daily_meal ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE food.daily_meal ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM_INIT';
ALTER TABLE food.daily_meal ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE food.daily_meal ADD COLUMN updated_by VARCHAR(255);

ALTER TABLE food.meal_ingredient ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE food.meal_ingredient ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM_INIT';
ALTER TABLE food.meal_ingredient ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE food.meal_ingredient ADD COLUMN updated_by VARCHAR(255);

ALTER TABLE food.meal_recipe ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE food.meal_recipe ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM_INIT';
ALTER TABLE food.meal_recipe ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE food.meal_recipe ADD COLUMN updated_by VARCHAR(255);

ALTER TABLE food.product ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE food.product ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM_INIT';
ALTER TABLE food.product ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE food.product ADD COLUMN updated_by VARCHAR(255);
