version: '3'
services:
  backend:
    build: ./Backend
    container_name: "backend"
    ports:
      - "8080:8080"
    depends_on:
      - database
  frontend:
    build: ./Frontend
    container_name: "frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend
  database:
    image: mongo:latest
    container_name: "database"
    restart: always
    ports:
      - 27017:27017
