image: docker:latest
services:
  - docker:dind

stages:
  - package
  - deploy

docker-build:
  stage: package
  script:
    - docker login -p $CI_BUILD_TOKEN -u $CI_USER registry.gitlab.com
    - docker build -t registry.gitlab.com/damian9449/improvement-app-frontend-2 .
    - docker push registry.gitlab.com/damian9449/improvement-app-frontend-2

docker-deploy:
  stage: deploy
  script:
    - apk add curl
    - curl https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
    - 'echo "token: $CI_KOYEB_KEY" > ~/.koyeb.yaml'
    - /root/.koyeb/bin/koyeb services update mutarexxii/prod --docker registry.gitlab.com/damian9449/improvement-app-frontend-2 --docker-private-registry-secret registry-front --ports 3000:http --routes /:3000
