image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

maven-build:
  stage: build
  image: maven:3.8.5-openjdk-17
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
    - docker login -p $CI_BUILD_TOKEN -u damian9449 registry.gitlab.com
    - docker build -t registry.gitlab.com/damian9449/improvement-app-backend .
    - docker push registry.gitlab.com/damian9449/improvement-app-backend

docker-deploy:
  stage: deploy
  script:
    - apk add curl
    - curl https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
    - 'echo "token: $CI_KOYEB_KEY" > ~/.koyeb.yaml'
    - /root/.koyeb/bin/koyeb services update mutarexii/backend --docker registry.gitlab.com/damian9449/improvement-app-backend --docker-private-registry-secret registry-front --ports 8080:http --routes /api:8080




# image: maven:3.8.3-openjdk-17
# 
# stages:          # List of stages for jobs, and their order of execution
#   - test
#   - build
#   - deploy

# maven-test:
#   stage: test
#   script: mvn test

# maven-build:
#   stage: build
#   script: mvn package
#   artifacts:
#     paths:
#       - target/*.jar

#app-deploy:
#  image: ubuntu:18.04
#  stage: deploy
#  script:
#    - apt-get update
#    - apt-get install -y lftp
#    - lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST -e "set ftp:ssl-allow off mirror -R target /app"
