spring:
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    mongodb:
      uri: ${MONGODB_URI}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://pgsql2.small.pl/p2222_food?reWriteBatchedInserts=true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile


server:
  port: 37786
  ssl:
    key-store: /home/mutarexx/domains/mutarexx.smallhost.pl/certs/keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: alias_name

path:
  file:
    excel: /home/mutarexx/tmp/

google:
  credentials:
    folder:
      path: file:/home/mutarexx/domains/mutarexx.smallhost.pl/google_token/serviceAccount.json

app:
  frontend:
    url: https://grindtrack.pl
  security:
    cookie:
      secure: true
      same-site: None  # frontend (grindtrack.pl) i API (mutarexx.smallhost.pl) to różne domeny
    cors:
      allowed-origins: "https://grindtrack.pl"