# MongoDB
spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: workout-app
      username: user_app
      password: user_app

  # Postgres
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    username: user_app
    password: user_app
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgresfood

  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
    enabled: true





# Docker Postgres
# docker run -d -p 5433:5432 --name some-postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=postgresfood postgres

# MySQL
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true&useSSL=false
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

# Docker MySQL
# docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=db -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -v /my/own/datadir:/var/lib/mysql -p 3307:3306 -d mysql:latest


