spring:
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    mongodb:
      uri: mongodb+srv://newUser:damian@cluster0.glh4o.mongodb.net/WorkoutApp?retryWrites=true&w=majority
      socket-timeout: 10000 # w milisekundach
      connect-timeout: 10000 # w milisekundach
  datasource:
    username: improvement-app-backend_postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-improvement-app-backend.alwaysdata.net:5432/improvement-app-backend_postgresfood?reWriteBatchedInserts=true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml

# Dokumentacja swagger / open API
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Aplikacja
path:
  file:
    excel: src/main/resources/tmp_files/

# Logging
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    io.hypersistence.utils: DEBUG
#    org.hibernate.type: TRACE









